### PR TITLE
Ensure consistent icon size, allow generateIndentCSS override, fix demo

### LINKED ISSUE #49: Exposing params or methods for CSS generation
@himdel

I think it could be possible to accept a `generateCss` function in the params. If it is not supplied the original one would be used and adding a helper method to get the tree depth. 

Or/And maybe I could add a function to return the generated CSS as a string, so the parent component could decide where to put it, or if multiple trees are on the page merge them. 

What do you think?

### PR DESCRIPTION
**Pull request by himdel**
Fixes #49 

Demo build was failing on an import, changed to a relative import,
and added normalize.css so that the demo uses the same reset stylesheet as the UI.

Added an optional `callbacks.generateIndentCSS` prop, a function to generate the indent css given max depth. Returning an empty string will disable css generation.

Updated css so that all icons are actually 1em + 4px wide total.

@brumik WDYT?

---

Before:

before

After normalize.css + border-box:

middle

After everything:

after

### CODE REVIEW

File: demo/src/Generator.tsx [hunk 1]
```diff
@@ -1,4 +1,5 @@
-import { HierarchicalNodeProps, TreeDataType } from 'react-wooden-tree';
+// import { HierarchicalNodeProps, TreeDataType } from 'react-wooden-tree';
+import { HierarchicalNodeProps, TreeDataType } from '../../src/';
```
Comment (brumik) [inline demo/src/Generator.tsx:2]: This was used with `npm link` to show that it is imported from the package, but I guess, it is more convenient like this.

File: src/components/Tree.tsx [hunk 2]
```diff
@@ -329,16 +329,28 @@ export class Tree extends React.PureComponent<TreeProps, {}> {
      * Generates the css classes for indenting the nodes.
      *
      * @param {number} depth Max depth of the tree. This is how many classes will be generated.
-     * @returns {string} CSS: .indent-X{padding-left:X*15px}
+     * @returns {string} CSS for .indent-X with and without .no-open-button
      */
-    private static generateIndentCSS(depth: number): string {
+    private static generateIndentCSS(depth: number, props: any): string {
```
Comment (brumik) [inline src/components/Tree.tsx:334]: Can we have the concrete function passed here instead of props? I know that Typescript is not that convenient, but I would like to keep params as specific as possible. (And please add the comment for the new param, it is used in the automatic documentation generation.)

File: demo/src/Generator.tsx (hunk 1 above)
Comment (himdel) [reply demo/src/Generator.tsx:2]: ah, looks like we can keep the name and use an alias, that also works :)

File: src/components/Tree.tsx (hunk 2 above)
Comment (himdel) [reply src/components/Tree.tsx]: Sure, added, and updated types :)

**Comment by himdel** [comment]
> Can you please generate new docs for it with npm docs after you updated the comments?

Well, `npm docs` doesn't really work, because it doesn't run it in a globstar supporting shell by default (so no `**`):

```
> react-wooden-tree@0.0.0-development docs /home/himdel/react-wooden-tree
> typedoc --out docs --name 'React Wodden Tree' --target es6 --excludePrivate --excludeProtected --excludeExternals --mode file src/**/{Tree,types}.tsx

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/home/himdel/react-wooden-tree/src/**/{Tree,types}.tsx'
    at Object.statSync (fs.js:855:3)
```

But running manually, with some additions worked, added :)

```
typedoc --out docs --name 'React Wodden Tree' --target es6 --excludePrivate --excludeProtected --excludeExternals --mode file src/**/{Tree,types}.tsx

# remove /home/himdel/react-wooden-tree references
perl -i -npe 's/.home.himdel.//' docs/**/*.*

# fix github/himdel references back to github/brumik
perl -i -npe 's#github.com/himdel#github.com/brumik#' docs/**/*.*
```

**Comment by himdel** [comment]
Should be ready @brumik  :)
